### ISSUE TITLE
I have successfully installed sumo-web3d, but the following error appears when starting the server. How can I solve it?

### ISSUE THREAD

**Issue by KangChou** [sidewalklabs/sumo-web3d#41]
```

$ python setup.py install
running install
running bdist_egg
running egg_info
creating sumo_web3d.egg-info
writing sumo_web3d.egg-info\PKG-INFO
writing dependency_links to sumo_web3d.egg-info\dependency_links.txt
writing entry points to sumo_web3d.egg-info\entry_points.txt
writing requirements to sumo_web3d.egg-info\requires.txt
writing top-level names to sumo_web3d.egg-info\top_level.txt
writing manifest file 'sumo_web3d.egg-info\SOURCES.txt'
reading manifest file 'sumo_web3d.egg-info\SOURCES.txt'

```

I have successfully installed sumo-web3d, but the following error appears when starting the server. How can I solve it?

```
 sumo-web3d
Traceback (most recent call last):
  File "D:\Users\Anaconda3\envs\tf2-gpu\Scripts\sumo-web3d-script.py", line 33, in <module>
    sys.exit(load_entry_point('sumo-web3d', 'console_scripts', 'sumo-web3d')())
  File "c:\sumo\tools\sumo-web3d\sumo_web3d\server\server.py", line 608, in run
    main(args)
  File "c:\sumo\tools\sumo-web3d\sumo_web3d\server\server.py", line 588, in main
    app = setup_http_server(task, SCENARIOS_PATH, scenarios)
  File "c:\sumo\tools\sumo-web3d\sumo_web3d\server\server.py", line 518, in setup_http_server
    functools.partial(scenario_attribute_route, scenario_file, scenarios, 'additional', None)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\aiohttp-4.0.0a1-py3.7-win-amd64.egg\aiohttp\web_urldispatcher.py", line 1069, in add_get
    resource.add_route(hdrs.METH_HEAD, handler, **kwargs)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\aiohttp-4.0.0a1-py3.7-win-amd64.egg\aiohttp\web_urldispatcher.py", line 294, in add_route
    expect_handler=expect_handler)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\aiohttp-4.0.0a1-py3.7-win-amd64.egg\aiohttp\web_urldispatcher.py", line 817, in __init__
    resource=resource)
  File "D:\Users\Anaconda3\envs\tf2-gpu\lib\site-packages\aiohttp-4.0.0a1-py3.7-win-amd64.egg\aiohttp\web_urldispatcher.py", line 144, in __init__
    ", got {!r}".format(handler))
TypeError: Only async functions are allowed as web-handlers , got functools.partial(<function send_as_http_response.<locals>.func_wrapper at 0x000001A7A4098048>, 'c:\\sumo\\tools\\sumo-web3d\\sumo_web3d\\server\\..\\scenarios.json', {'bologna-acosta': <sumo_web3d.server.server.Scenario object at 0x000001A7A40A3E48>, 'downtown-toronto': <sumo_web3d.server.server.Scenario object at 0x000001A7A6512B88>, 'queens-quay': <sumo_web3d.server.server.Scenario object at 0x000001A7A4099848>, 'cross3ltl': <sumo_web3d.server.server.Scenario object at 0x000001A7A40C8108>, 'pedestring-striping': <sumo_web3d.server.server.Scenario object at 0x000001A7A4099A48>, 'person-number': <sumo_web3d.server.server.Scenario object at 0x000001A7A4F70BC8>}, 'additional', None)
(tf2-gpu)

```

**Comment by KangChou** [comment]
Due to the error, I tried to install Q, but it didn't solve the problem. I operated in Windows 10.
How to solve the above problems?

` pip install -r requirements.txt yarn
Looking in indexes: https://pypi.python.org/simple/
Obtaining file:///C:/Sumo/tools/sumo-web3d (from -r requirements.txt (line 4))
Collecting yarn
  Downloading yarn-0.0.9-py3-none-any.whl (128 kB)
Requirement already satisfied: flake8==3.4.1 in d:\users`

**Comment by KangChou** [comment]
I use Ubuntu 18. 04 also has the same error

**Comment by KangChou** [comment]
@sidewalklabs

**Comment by KangChou** [comment]
`sumo-web3d
Traceback (most recent call last):
......
TypeError: Only async functions are allowed as web-handlers , got functools.partial(<function send_as_http_response.<locals>.func_wrapper at 0x7f00fe1535f0>, '/home/dus/anaconda3/envs/tf20-gpu/lib/python3.7/site-packages/sumo_web3d-1.0.1-py3.7.egg/sumo_web3d/server/../scenarios.json', {'bologna-acosta': <sumo_web3d.server.server.Scenario object at 0x7f00fe0d5290>, 'downtown-toronto': <sumo_web3d.server.server.Scenario object at 0x7f00fdc7f910>, 'queens-quay': <sumo_web3d.server.server.Scenario object at 0x7f00fe0f4250>, 'cross3ltl': <sumo_web3d.server.server.Scenario object at 0x7f00fe0d5050>, 'pedestring-striping': <sumo_web3d.server.server.Scenario object at 0x7f00fe148cd0>, 'person-number': <sumo_web3d.server.server.Scenario object at 0x7f00fe148ed0>}, 'additional', None)
`
