### ISSUE TITLE
Failed to start server

### ISSUE THREAD

**Issue by alexdawn** [sidewalklabs/sumo-web3d#6]
From a fresh install of sumo-web3d and SUMO_HOME set to `C:/Program Files (x86)/DLR/Sumo`
`sumo-web3d` fails to run

See below for the error log:
```
$ sumo-web3d
Traceback (most recent call last):
  File "c:\tools\anaconda\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\anaconda\Scripts\sumo-web3d.exe\__main__.py", line 9, in <module>
  File "c:\tools\anaconda\lib\site-packages\sumo_web3d\server\server.py", line 596, in run
    main(args)
  File "c:\tools\anaconda\lib\site-packages\sumo_web3d\server\server.py", line 560, in main
    scenarios = load_scenarios_file({}, SCENARIOS_PATH)
  File "c:\tools\anaconda\lib\site-packages\sumo_web3d\server\server.py", line 471, in load_scenarios_file
    scenario = Scenario.from_config_json(new_scenario)
  File "c:\tools\anaconda\lib\site-packages\sumo_web3d\server\server.py", line 119, in from_config_json
    for xml in [parse_xml_file(f) for f in additional_files]:
  File "c:\tools\anaconda\lib\site-packages\sumo_web3d\server\server.py", line 119, in <listcomp>
    for xml in [parse_xml_file(f) for f in additional_files]:
  File "c:\tools\anaconda\lib\site-packages\sumo_web3d\server\xml_utils.py", line 10, in parse_xml_file
    return xmltodict.parse(f.read(), attr_prefix='')
  File "c:\tools\anaconda\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 27814: character maps to <undefined>
```

**Comment by jdglicktraffic** [comment]
Same issue. Any resolution?  I am running on Windows.

**Comment by danvk** [comment]
Sorry for the lack of response on this. I don't have access to a Windows machine so this is hard for me to debug.

Just double-checking that you're on Python 3.6?

**Comment by levente-s** [comment]
Hi,
I have the same issue. The reason is that _xmltodict.parse_ fails on the file _toronto.poly.xml_.
(note that it is still possible to provide your own config like this: sumo-web3d -c sumo.cfg).

Work-around: remove _"downtown-toronto"_ scenario from scenarios.json

My environment:
Windows 10
Python 3.6.5
xmltodict 0.11.0

Strings like the following seems to be problematic:
Возера Антарыа
Ïce Condominums at York Centre
ఒన్ టారియో
加拿大國家電視塔
מגדל סי אן

Regards,
Levente

**Comment by danvk** [comment]
Thanks for the details. Could someone try changing this line:
https://github.com/sidewalklabs/sumo-web3d/blob/cbb8488f7f4a7a6112cc4a617a52e0a9e02dc339/sumo_web3d/server/xml_utils.py#L9

to

```python
        with open(filepath, encoding='utf-8') as f:
```

and report back whether this fixes the issue?

(see https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character)

**Comment by levente-s** [comment]
I have tried it and it works, this change fixes the issue.

**Comment by danvk** [comment]
I've pushed a new version of sumo-web3d to PyPI (1.0.1) which includes this fix. Thanks for the feedback!

**Comment by alexdawn** [comment]
Thank you for posting the update it now works on my machine!
