### ISSUE TITLE
rou file not accessible

### ISSUE THREAD

**Issue by uwmyuan** [sidewalklabs/sumo-web3d#9]
Hi, this is a nice work. I tried it, however, got the following error on Win10 with SUMO 1.1.0. Maybe the mixed use of slash and backslack and bad path `.../joined.rou.xml joined_busses.rou.xml` lead the problem.
```
(base) ...>sumo-web3d
Listening on:
    127.0.0.1:5000 (HTTP)
    127.0.0.1:5678 (WebSockets)

Switching to bologna-acosta
Executing ...\Sumo\bin\sumo -c ...\sumo_web3d\server\..\scenarios/bologna-acosta/run.sumo.cfg
Loading configuration... done.
Error: The route file '...\sumo_web3d\server\..\scenarios/bologna-acosta/joined.rou.xml joined_busses.rou.xml' is not accessible.
Quitting (on error).
Error in connection handler
Traceback (most recent call last):
  File "...\websockets\server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "...\sumo_web3d\server\server.py", line 309, in websocket_simulation_control
    sumo_start_fn()
  File "...\sumo_web3d\server\server.py", line 565, in <lambda>
    lambda: sumo_start_fn(getattr(current_scenario, 'config_file')),
  File "...\sumo_web3d\server\server.py", line 339, in start_sumo_executable
    traci.start(args)
  File "...\Sumo\tools\traci\__init__.py", line 99, in start
    return getVersion()
  File "...\Sumo\tools\traci\__init__.py", line 208, in getVersion
    return _connections[""].getVersion()
  File "...\Sumo\tools\traci\connection.py", line 337, in getVersion
    result = self._sendExact()
  File "...\Sumo\tools\traci\connection.py", line 99, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
Traceback (most recent call last):
  File "...\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\sumo-web3d.exe\__main__.py", line 9, in <module>
  File "...\sumo_web3d\server\server.py", line 596, in run
    main(args)
  File "...\sumo_web3d\server\server.py", line 591, in main
    loop.run_forever()
  File "...\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "...\lib\asyncio\base_events.py", line 1390, in _run_once
    event_list = self._selector.select(timeout)
  File "...\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "...\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt
```
After avoiding use of the relative dir in myown testing files, I cannot get the vehicle animation either.
In the browser,
```
Stats
time: 0.000 s
payload: 0.0 KB
simulate: 0.00 ms
snapshot: 0.00 ms
Vehicle Summary
Click Summary
N/A
```
In the cmd,
```
(base) ...>sumo-web3d -c "...\sim.sumocfg"
Listening on:
    127.0.0.1:5000 (HTTP)
    127.0.0.1:5678 (WebSockets)

Switching to sim.sumocfg
Switching to sim.sumocfg
Executing ...\Sumo\bin\sumo -c ...\sim.sumocfg
Loading configuration... done.
***Starting server on port 16902 ***
Loading net-file from '...\sim.net.xml'... done (2ms).
Warning: Missing yellow phase in tlLogic '65', program '65' for tl-index 0 when switching to phase 1
Loading done.
Simulation started with time: 0.00
...\Sumo\tools\traci\domain.py:113: UserWarning: The domain trafficlights is deprecated, use trafficlight instead.
  self._name, self._deprecatedFor))  # , DeprecationWarning)
```

**Comment by uwmyuan** [comment]
@danvk Thanks for the quick response. I'll test this and reply later.

**Comment by uwmyuan** [comment]
@danvk I tested with `SUMO 0.32`, it worked well. The problem is due to the compatibility with `SUMO 1.x`.
And when `yarn` from source code there was a warning `info fsevents@1.1.2: The platform "win32" is incompatible with this module.`
